site_name: mcp-email-server
repo_url: https://github.com/wh1isper/mcp-email-server
site_url: https://mcp-email-server.wh1isper.top
site_description: IMAP and SMTP via MCP Server
site_author: wh1isper
edit_uri: edit/main/docs/
repo_name: wh1isper/mcp-email-server
copyright: Maintained by <a href="https://github.com/wh1isper">wh1isper</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["mcp_email_server"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wh1isper/mcp-email-server
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/mcp-email-server

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
